import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "../components/pages/footer";
import { Header } from "../components/pages/header";
import { AuthProvider } from "../components/auth/authProvider";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        
          <Header />
                <AuthProvider>
          <main className="min-h-screen bg-white text-zinc-950"> {children} </main>
        </AuthProvider>
       
          <Footer/>

          </body>
    </html>
  );
}
